### ISSUE TITLE
@tags with underscore in them are not highlighted fully

### ISSUE THREAD

**Issue by ianrenauld** [Blodwynn/.feature-file-syntax-highlight-Cucumber-#1]
If I have a tag in the form of @admin_api, it seems that only the part before the underscore is properly highlighted, the rest is the color of normal text.

![tag_highlight](https://user-images.githubusercontent.com/16843123/51853628-bd9d1b80-22f6-11e9-85e8-b71a90c416c5.png)

I wasn't 100% sure if the underscore is an accepted character, but it seems that the Cucumber documentation uses them in some examples, so I assume it should be ok. See https://docs.cucumber.io/cucumber/api/#development-process for example.

**Comment by Blodwynn** [comment]
Hello!

Thanks for reporting this issue, I'll fix it by tomorrow. 👍

**Comment by Blodwynn** [comment]
Sorry, got sick meanwhile. Fix is out with 1.6.3 version. :)
