### ISSUE TITLE
Wrong line comment character?

### ISSUE THREAD

**Issue by ianrenauld** [Blodwynn/.feature-file-syntax-highlight-Cucumber-#2]
According to https://docs.cucumber.io/gherkin/reference/ the proper character to use to mark a line as a comment in a Gherkin feature file is `#`.  This extension presently uses `//` and also uses `/* */` for multi-line comments, which I believe are not supported in Gherkin (some people use `"""` to simulate multi-line comments, but these normally mark doc strings).

Anyway, I think this extension should at least use `#` instead of `//`. You can change this on line 4 of the `language-configuration.json` file. I leave it up to you if you want to simulate multi-line comments with `"""` or not, but clearly `/* */` is not right.

Really love this extension, but this comment thing is bugging me!

**Comment by Blodwynn** [comment]
Thanks for reporting this! This extension still suffers of some early bugs I'm afraid. :( :)
Again thanks a lot for the report! :)

**Comment by Blodwynn** [comment]
Fixed that language-configuration file. Fix is it out with 1.6.4.

Thanks for your support Ian!
