### ISSUE TITLE
Highlight "Scenarios" like "Examples" in Scenario Outline

### ISSUE THREAD

**Issue by Roterfux** [Blodwynn/.feature-file-syntax-highlight-Cucumber-#3]
See Gherkin documentation https://docs.cucumber.io/gherkin/reference/#scenario-outline

In my tests I do not always use examples, but also Scenarios as title for the following table.
I checked with the official documentation and they do allow both. Please update the extention to also support "Scenarios"

e.g.
Scenario outline: my test
Given I have entered <input_1> into the calculator
And I have entered <input_2> into the calculator
When I press <button>
Then the result should be <output> on the screen
    
Scenarios:
   | input_1 | input_2 | button | output |
   | 20      | 30      | add    | 50     |
   | 2       | 5       | add    | 7      |

**Comment by Blodwynn** [comment]
Thanks for reporting this issue, I'll fix it in a bit. :)

**Comment by Blodwynn** [comment]
The fix for the issue is rolled out now with 1.7.1. Check for updates and it should be alright. :)

**Comment by Roterfux** [comment]
Looking forward onto the v1.7.1 release. It's not yet there ...

**Comment by Roterfux** [comment]
great. it works. thx!!

**Comment by Blodwynn** [comment]
Glad you like it! 👍
