### ISSUE TITLE
Header of example table with title isn't hightlighted

### ISSUE THREAD

**Issue by seungho100** [Blodwynn/.feature-file-syntax-highlight-Cucumber-#5]
![image](https://user-images.githubusercontent.com/67997110/90094858-021dca00-dd6a-11ea-8a0c-409e7e8db436.png)

As you see in the image above, header of example table with title isn't highlighted.

**Comment by Blodwynn** [comment]
Hi, thanks for noting, will fix it asap. :)

**Comment by Blodwynn** [comment]
Expect this bug to be fixed in version 1.8.0.
